### ISSUE TITLE
Petting zoo Sisl

### ISSUE THREAD

**Issue by prinshul** [Replicable-MARL/MARLlib#117]
Hi

Can you please provide support for petting zoo Sisl environments like waterworld, multi walker etc 

Thanks

**Comment by Theohhhu** [comment]
Hi,

SISL has been added in PR #125. Related docs can be found [here](https://marllib.readthedocs.io/en/latest/handbook/env.html#sisl).

If you have any further questions or need assistance, feel free to ask.

**Comment by prinshul** [comment]
marllib/marl/algos/hyperparams/finetuned has no sisl.

I ran the sisl with hyperparameters from marllib/marl/algos/hyperparams/common
like this:
mappo = marl.algos.mappo(hyperparam_source="common")

As this is giving an error:
mappo = marl.algos.mappo(hyperparam_source="sisl")

**Comment by prinshul** [comment]
flattening self.obstacle_coords to 1D with self.obstacle_coords.ravel() works.

**Comment by Theohhhu** [comment]
> marllib/marl/algos/hyperparams/finetuned has no sisl.
> 
> I ran the sisl with hyperparameters from marllib/marl/algos/hyperparams/common like this: mappo = marl.algos.mappo(hyperparam_source="common")
> 
> As this is giving an error: mappo = marl.algos.mappo(hyperparam_source="sisl")

SISL has not been finetuned, using `hyperparam_source="sisl"` is not permissible.

**Comment by prinshul** [comment]
Getting the following error in both multiwalker and waterworld:

Failure # 1 (occurred at 2023-06-16_00-24-06)
Traceback (most recent call last):
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 892, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ^[[36mray::MAPPOTrainer.train()^[[39m (pid=30214, ip=10.208.66.213, repr=MAPPOTrainer)
  File "/home/prashant/marl/MARLlib/marllib/marl/algos/core/CC/mappo.py", line 64, in central_critic_ppo_loss
    loss = func(policy, model, dist_class, train_batch)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/rllib/agents/ppo/ppo_torch_policy.py", line 46, in ppo_surrogate_loss
    curr_action_dist = dist_class(logits, model)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/rllib/models/torch/torch_action_dist.py", line 186, in __init__
    self.dist = torch.distributions.normal.Normal(mean, torch.exp(log_std))
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/torch/distributions/normal.py", line 50, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (9600, 2)) of distribution Normal(loc: torch.Size([9600, 2]), scale: torch.Size([9600, 2])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        ...,
        [nan, nan],
        [nan, nan],
        [nan, nan]], device='cuda:0', grad_fn=<SplitBackward0>)

The above exception was the direct cause of the following exception:

^[[36mray::MAPPOTrainer.train()^[[39m (pid=30214, ip=10.208.66.213, repr=MAPPOTrainer)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 682, in train
    raise e
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 668, in train
    result = Trainable.train(self)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/tune/trainable.py", line 283, in train
    result = self.step()
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/rllib/agents/trainer_template.py", line 206, in step
    step_results = next(self.train_exec_impl)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/util/iter.py", line 791, in apply_foreach
    result = fn(item)
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/rllib/execution/train_ops.py", line 213, in __call__
    results = policy.learn_on_loaded_batch(
  File "/home/iitdpc/miniconda3/envs/marllib1/lib/python3.9/site-packages/ray/rllib/policy/torch_policy.py", line 658, in learn_on_loaded_batch

**Comment by Theohhhu** [comment]
I'm unsure about the specific issue at hand. However, the script provided below runs without any problems on my local server.
```
from marllib import marl

env = marl.make_env(environment_name="sisl", map_name="multiwalker", force_coop=True)

mappo = marl.algos.mappo(hyperparam_source="test")

model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})

mappo.fit(env, model, stop={'episode_reward_mean': 2000, 'timesteps_total': 20000000}, local_mode=False, num_gpus=1,
          num_workers=2, share_policy='all', checkpoint_freq=100)
```

Additionally, the mentioned modification is not required in order to run the script successfully.

> flattening self.obstacle_coords to 1D with self.obstacle_coords.ravel() works.

**Comment by prinshul** [comment]
> I'm unsure about the specific issue at hand. However, the script provided below runs without any problems on my local server.
> 
> ```
> from marllib import marl
> 
> env = marl.make_env(environment_name="sisl", map_name="multiwalker", force_coop=True)
> 
> mappo = marl.algos.mappo(hyperparam_source="test")
> 
> model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})
> 
> mappo.fit(env, model, stop={'episode_reward_mean': 2000, 'timesteps_total': 20000000}, local_mode=False, num_gpus=1,
>           num_workers=2, share_policy='all', checkpoint_freq=100)
> ```
> 
> Additionally, the mentioned modification is not required in order to run the script successfully.
> 
> > flattening self.obstacle_coords to 1D with self.obstacle_coords.ravel() works.

With lower LR in mappo.yaml as 1e-6 (original is 5e-4), I am able to run it for for 2e7 timesteps without any error.
