### ISSUE TITLE
Hide and Seek environment problem

### ISSUE THREAD

**Issue by wakaka821** [Replicable-MARL/MARLlib#151]
This is a good multi-agent reinforcement learning tool. I was interested in the Hide and Seek environment and ran the following code。

from marllib import marl
env = marl.make_env(environment_name="hns", map_name="BoxLocking")
mappo = marl.algos.mappo(hyperparam_source='mpe')
model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})
mappo.fit(env, model, stop={'timesteps_total': 1000000}, share_policy='individual')

But after a few training sessions, something went wrong. The following is the contents of the error. txt record.

Failure # 1 (occurred at 2023-07-14_16-12-43)
Traceback (most recent call last):
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): [36mray::MAPPOTrainer.train()[39m (pid=1248016, ip=10.1.77.110, repr=MAPPOTrainer)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 679, in train
    raise e
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 668, in train
    result = Trainable.train(self)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 283, in train
    result = self.step()
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 206, in step
    step_results = next(self.train_exec_impl)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 876, in apply_flatten
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
ray.exceptions.RayTaskError(ValueError): [36mray::RolloutWorker.par_iter_next()[39m (pid=1248026, ip=10.1.77.110, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fa9c8bf0a90>)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/util/iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 378, in gen_rollouts
    yield self.sample()
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 753, in sample
    batches = [self.input_reader.next()]
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 103, in next
    batches = [self.get_data()]
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 233, in get_data
    item = next(self._env_runner)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 599, in _env_runner
    _process_observations(
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 815, in _process_observations
    prep_obs = preprocessor.transform(raw_obs)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 296, in transform
    self.check_shape(observation)
  File "/home/lenovo/.conda/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 93, in check_shape
    raise ValueError(
ValueError: ('Observation ({} dtype={}) outside given space ({})!', {'obs': array([ 4.8536258e+00,  2.1419249e+00,  9.2836031e-05,  2.8040111e+00,
        2.3712777e-02, -3.2882891e+00,  4.0063977e-01, -1.8000000e+00,
        6.9000000e-01,  1.0000000e+00,  1.0000000e+00,  1.9247375e-01,
        1.9827447e+00, -8.4265521e-05,  5.4209743e+00, -1.2653337e+00,
       -2.9588826e+00, -1.7857215e-01, -1.0142149e-12,  0.0000000e+00,
        1.0000000e+00,  4.2167959e+00,  1.5645610e-01, -1.1585753e-05,
        9.9968684e-01, -2.5025228e-02, -1.5215031e-18,  2.5075254e-19,
       -5.7609755e-17, -1.0926804e-18,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  3.5138693e+02,  1.9317213e+02,  5.5738658e-02,
       -6.1336976e-01,  7.8979588e-01,  5.5854172e+01,  4.0277466e+01,
       -3.3299942e+00,  3.7561845e-02,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00], dtype=float32)}, None, Dict(obs:Box([-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.
 -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.
 -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.
 -100. -100. -100. -100. -100. -100. -100. -100. -100.], [100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100.], (45,), float32)))

How can I solve this problem? Thank you very much.

**Comment by Theohhhu** [comment]
Hello, thank you for bringing this to our attention.

You can modify the scenario name to `empty` by following this link: [here](https://github.com/Replicable-MARL/MARLlib/blob/0ac275e6132e653f826b107e79963a1485bcd425/marllib/envs/base_env/config/hns.yaml#L27). This is the regulation of original repository for the Hide and Seek where you can find at our [docs](https://marllib.readthedocs.io/en/latest/handbook/env.html).

On my local server, the script you provide should run at least 20 training iterations without error.

**Comment by wakaka821** [comment]
> env = marl.make_env(environment_name="hns", map_name="BoxLocking")
Thank you for your reply. When map_name="BoxLocking", the training is fine, but when map_name="hidenseek", the same problem occurs.

**Comment by Theohhhu** [comment]
Running smoothly on my server for 100 iterations:

```
env = marl.make_env(environment_name="hns", map_name="hidenseek")
mappo = marl.algos.mappo(hyperparam_source="test")
model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})
mappo.fit(env, model, stop={'episode_reward_mean': 2000, 'timesteps_total': 20000000}, local_mode=True, num_gpus=1,
          num_workers=2, share_policy='individual', checkpoint_freq=500)
```
with env config:
```
env_args:
  scenario_name: "quadrant" # "quadrant" only for hidenseek | otherwise "empty"
  task_type: "all-return"
  num_agents: 2
  num_seekers: 1
  num_hiders: 1
  num_boxes: 1
  num_ramps: 1
  num_food: 0
  floor_size: 6.0
  grid_size: 30
  fixed_door: True
  spawn_obs: False
  env_horizon: 100
  share_reward: False
  seed: 123
```
Any details on the error triggered condition on your side?

**Comment by wakaka821** [comment]
No problems occurred during the training phase. Thank you for helping me solve the problem. 
At the same time, I tried running the following code to load the model and render the environment.

env = marl.make_env(environment_name="hns", map_name="hidenseek")
mappo = marl.algos.mappo(hyperparam_source="test")
model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-256"})
mappo.render(env, model, local_mode=True, share_policy='individual', restore_path={'params_path': "/home/exp_results/mappo_mlp_hidenseek/MAPPOTrainer_hns_hidenseek_141b0_00000_0_2023-07-24_11-20-45/params.json",'model_path':"/home/exp_results/mappo_mlp_hidenseek/MAPPOTrainer_hns_hidenseek_141b0_00000_0_2023-07-24_11-20-45/checkpoint_000050/checkpoint-50"})

But the hide and seek environment was not rendered in the new window and there was no error, the following is the display result in the terminal.

actor_name: MAPPOTrainer
2023-07-24 11: 25: 03, 806 INFO trainable.py: 416 - - Restored on 10.1.77.215 from checkpoint: / home/exp_results/mappo_mlp_hidenseek/MAPPOTrainer_hns_hidenseek_ad72e_00000_0_2023-07-24_11-25-03/tmp582p2quarestore_from_object/checkpoint-50
2023-07-24 11: 25: 03, 807 INFO trainable.py: 424 - - Current state after restoring: {'_iteration': 50, '_timesteps_total': 0, '_time_total': 57.54179382324219, '_episodes_total': 100}
== Status ==
Current time: 2023-07-24 11: 25: 03 (running for 00: 00: 00.76)
Memory usage on this node: 6.0/15.5 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 1.0/1 GPUs, 0.0/6.54 GiB heap, 0.0/3.27 GiB objects(0.0/1.0 accelerator_type: P1000)
Result logdir: / home/exp_results/mappo_mlp_hidenseek
Number of trials: 1/1 (1 RUNNING)
+----------------------------------------+----------+-------------------+
| Trial name | status | loc |
|----------------------------------------+----------+-------------------|
| MAPPOTrainer_hns_hidenseek_ad72e_00000 | RUNNING | 10.1.77.215: 14948 |
+----------------------------------------+----------+-------------------+

2023-07-24 11: 25: 03, 868 WARNING deprecation.py: 38 - - DeprecationWarning: `policy_mapping_fn(agent_id)` has been deprecated. Use `policy_mapping_fn(agent_id, episode, worker, **kwargs)` instead. This will raise an error in the future!
2023-07-24 11: 25: 57, 359 WARNING util.py: 165 - - The `process_trial_restore` operation took 53.538 s, which may be a performance bottleneck.
== Status ==
Current time: 2023-07-24 11: 25: 57 (running for 00: 00: 54.30)
Memory usage on this node: 6.1/15.5 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/12 CPUs, 1.0/1 GPUs, 0.0/6.54 GiB heap, 0.0/3.27 GiB objects(0.0/1.0 accelerator_type: P1000)
Result logdir: / home/exp_results/mappo_mlp_hidenseek
Number of trials: 1/1 (1 RUNNING)
+----------------------------------------+----------+-------------------+
| Trial name | status | loc |
|----------------------------------------+----------+-------------------|
| MAPPOTrainer_hns_hidenseek_ad72e_00000 | RUNNING | 10.1.77.215: 14948 |
+----------------------------------------+----------+-------------------+

== Status ==
Current time: 2023-07-24 11: 25: 57 (running for 00: 00: 54.88)
Memory usage on this node: 6.1/15.5 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/12 CPUs, 0/1 GPUs, 0.0/6.54 GiB heap, 0.0/3.27 GiB objects(0.0/1.0 accelerator_type: P1000)
Result logdir: / home/exp_results/mappo_mlp_hidenseek
Number of trials: 1/1 (1 TERMINATED)
+----------------------------------------+------------+-------------------+--------+------------------+-------+----------+----------------------+----------------------+--------------------+
| Trial name | status | loc | iter | total time(s) | ts | reward | episode_reward_max | episode_reward_min | episode_len_mean |
|----------------------------------------+------------+-------------------+--------+------------------+-------+----------+----------------------+----------------------+--------------------|
| MAPPOTrainer_hns_hidenseek_ad72e_00000 | TERMINATED | 10.1.77.215: 14948 | 51 | 111.076 | 10200 | 0 | 0 | 0 | 100 |
+----------------------------------------+------------+-------------------+--------+------------------+-------+----------+----------------------+----------------------+--------------------+

2023-07-24 11: 25: 58, 041 INFO tune.py: 630 - - Total run time: 55.10 seconds(54.81 seconds for the tuning loop).

**Comment by Theohhhu** [comment]
You should incorporate the render function into [hide and seek](https://github.com/Replicable-MARL/MARLlib/blob/master/marllib/envs/base_env/hns.py). For guidance, you can take reference from the [MPE example](https://github.com/Replicable-MARL/MARLlib/blob/e2b1a9db859b6a73a1e6330781f91dc14e5fd9b9/marllib/envs/base_env/mpe.py#L139) on how to implement it.

Please note that the rendering function might vary from one environment to another. Therefore, if you develop one, we would appreciate it if you submit a pull request (PR) to include it into MARLlib!
