### ISSUE TITLE
Error processing restore.

### ISSUE THREAD

**Issue by hccz95** [Replicable-MARL/MARLlib#170]
I successfully fit my model, but failed to restore and render.

part of my code:
```python
    env = marl.make_env(environment_name="magym", map_name="FortAttackOffense", abs_path=path)

    # pick mappo algorithms
    mappo = marl.algos.mappo(hyperparam_source="test")
    # customize model
    model = marl.build_model(env, mappo, {"core_arch": "mlp", "encode_layer": "128-128"})

    # start learning
    mappo.fit(env, model, stop={'episode_reward_mean': 9.5, 'timesteps_total': 30000000}, local_mode=False, num_gpus=1,
              num_workers=32, share_policy='individual', checkpoint_freq=10)

    # rendering
    mappo.render(
        env, model,
        local_mode=True,
        restore_path={
            'params_path': "exp_results/mappo_mlp_FortAttackOffense/MAPPOTrainer_magym_FortAttackOffense_11dac_00000_0_2023-07-30_00-22-10/params.json",
            'model_path': "exp_results/mappo_mlp_FortAttackOffense/MAPPOTrainer_magym_FortAttackOffense_11dac_00000_0_2023-07-30_00-22-10/checkpoint_000070/checkpoint-70"
        },
        num_workers=0,
    )
```

console output:
```
(base) root@kk:/workspaces/FortAttack# xvfb-run python test_fortattack_marllib_env.py 
/workspaces/FortAttack/./marllib_env/fortattack.yaml
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| Env_Name           | Check_Status   | Error_Log                                                            | Config_File_Location                         | Env_File_Location                   |
+====================+================+======================================================================+==============================================+=====================================+
| gymnasium_mamujoco | Error          | No module named 'gymnasium_robotics'                                 | envs/base_env/config/gymnasium_mamujoco.yaml | envs/base_env/gymnasium_mamujoco.py |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| mpe                | Ready          | Null                                                                 | envs/base_env/config/mpe.yaml                | envs/base_env/mpe.py                |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| mamujoco           | Error          | No module named 'multiagent_mujoco'                                  | envs/base_env/config/mamujoco.yaml           | envs/base_env/mamujoco.py           |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| smac               | Error          | No module named 'smac'                                               | envs/base_env/config/smac.yaml               | envs/base_env/smac.py               |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| football           | Error          | No module named 'gfootball'                                          | envs/base_env/config/football.yaml           | envs/base_env/football.py           |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| magent             | Error          | cannot import name 'adversarial_pursuit_v3' from 'pettingzoo.magent' | envs/base_env/config/magent.yaml             | envs/base_env/magent.py             |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| rware              | Error          | No module named 'rware'                                              | envs/base_env/config/rware.yaml              | envs/base_env/rware.py              |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| lbf                | Error          | No module named 'lbforaging'                                         | envs/base_env/config/lbf.yaml                | envs/base_env/lbf.py                |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| pommerman          | Error          | No module named 'pommerman'                                          | envs/base_env/config/pommerman.yaml          | envs/base_env/pommerman.py          |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| hanabi             | Ready          | Null                                                                 | envs/base_env/config/hanabi.yaml             | envs/base_env/hanabi.py             |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| metadrive          | Error          | No module named 'metadrive'                                          | envs/base_env/config/metadrive.yaml          | envs/base_env/metadrive.py          |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| mate               | Error          | No module named 'mate'                                               | envs/base_env/config/mate.yaml               | envs/base_env/mate.py               |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| gobigger           | Error          | No module named 'gobigger'                                           | envs/base_env/config/gobigger.yaml           | envs/base_env/gobigger.py           |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| overcooked         | Error          | No module named 'overcooked_ai_py'                                   | envs/base_env/config/overcooked.yaml         | envs/base_env/overcooked.py         |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| voltage            | Error          | No module named 'pandapower'                                         | envs/base_env/config/voltage.yaml            | envs/base_env/voltage.py            |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| aircombat          | Error          | No module named 'jsbsim'                                             | envs/base_env/config/aircombat.yaml          | envs/base_env/aircombat.py          |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| hns                | Error          | No module named 'mujoco_worldgen'                                    | envs/base_env/config/hns.yaml                | envs/base_env/hns.py                |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| sisl               | Error          | cannot import name 'multiwalker_v7' from 'pettingzoo.sisl'           | envs/base_env/config/sisl.yaml               | envs/base_env/sisl.py               |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
| magym              | Ready          | Null                                                                 | envs/base_env/config/magym.yaml              | envs/base_env/magym.py              |
+--------------------+----------------+----------------------------------------------------------------------+----------------------------------------------+-------------------------------------+
2023-07-30 01:25:42,556 WARNING sample.py:401 -- DeprecationWarning: wrapping <function run_cc.<locals>.<lambda> at 0x7fdc6e4e7b80> with tune.function() is no longer needed
2023-07-30 01:25:42,743 WARNING worker.py:496 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
:task_name:bundle_reservation_check_func
:actor_name:MAPPOTrainer
2023-07-30 01:25:42,855 WARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!
2023-07-30 01:25:42,855 INFO ppo.py:166 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
2023-07-30 01:25:42,856 INFO trainer.py:770 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2023-07-30 01:25:42,933 WARNING deprecation.py:38 -- DeprecationWarning: `SampleBatch['is_training']` has been deprecated. Use `SampleBatch.is_training` instead. This will raise an error in the future!
2023-07-30 01:25:42,991 WARNING trainer_template.py:185 -- `execution_plan` functions should accept `trainer`, `workers`, and `config` as args!
2023-07-30 01:25:42,991 WARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!
2023-07-30 01:25:43,046 WARNING util.py:57 -- Install gputil for GPU system monitoring.
:actor_name:MAPPOTrainer
[2023-07-30 01:25:43,091 E 33552 33552] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::MAPPOTrainer.restore_from_object() (pid=33552, ip=10.26.1.123, repr=MAPPOTrainer)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/tune/trainable.py", line 433, in restore_from_object
    self.restore(checkpoint_path)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/tune/trainable.py", line 411, in restore
    self.load_checkpoint(checkpoint_path)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 830, in load_checkpoint
    self.__setstate__(extra_data)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 289, in __setstate__
    Trainer.__setstate__(self, state)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1813, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1275, in restore
    self.sync_filters(objs["filters"])
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1237, in sync_filters
    assert all(k in new_filters for k in self.filters)
AssertionError at time: 1.69065e+09
2023-07-30 01:25:43,103 ERROR syncer.py:75 -- Log sync requires rsync to be installed.
== Status ==
Current time: 2023-07-30 01:25:43 (running for 00:00:00.49)
Memory usage on this node: 8.6/62.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 1.0/48 CPUs, 0/4 GPUs, 0.0/36.76 GiB heap, 0.0/18.38 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /workspaces/FortAttack/exp_results/mappo_mlp_FortAttackOffense
Number of trials: 1/1 (1 RUNNING)
+--------------------------------------------------+----------+-------------------+
| Trial name                                       | status   | loc               |
|--------------------------------------------------+----------+-------------------|
| MAPPOTrainer_magym_FortAttackOffense_f1da7_00000 | RUNNING  | 10.26.1.123:33552 |
+--------------------------------------------------+----------+-------------------+


2023-07-30 01:25:43,117 ERROR trial_runner.py:1124 -- Trial MAPPOTrainer_magym_FortAttackOffense_f1da7_00000: Error processing restore.
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 1117, in _process_trial_restore
    self.trial_executor.fetch_result(trial)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::MAPPOTrainer.restore_from_object() (pid=33552, ip=10.26.1.123, repr=MAPPOTrainer)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/tune/trainable.py", line 433, in restore_from_object
    self.restore(checkpoint_path)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/tune/trainable.py", line 411, in restore
    self.load_checkpoint(checkpoint_path)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 830, in load_checkpoint
    self.__setstate__(extra_data)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 289, in __setstate__
    Trainer.__setstate__(self, state)
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 1813, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1275, in restore
    self.sync_filters(objs["filters"])
  File "/opt/miniconda/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1237, in sync_filters
    assert all(k in new_filters for k in self.filters)
AssertionError
== Status ==
Current time: 2023-07-30 01:25:43 (running for 00:00:01.15)
Memory usage on this node: 8.6/62.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/48 CPUs, 0/4 GPUs, 0.0/36.76 GiB heap, 0.0/18.38 GiB objects (0.0/1.0 accelerator_type:G)
Result logdir: /workspaces/FortAttack/exp_results/mappo_mlp_FortAttackOffense
Number of trials: 1/1 (1 ERROR)
+--------------------------------------------------+----------+-------------------+
| Trial name                                       | status   | loc               |
|--------------------------------------------------+----------+-------------------|
| MAPPOTrainer_magym_FortAttackOffense_f1da7_00000 | ERROR    | 10.26.1.123:33552 |
+--------------------------------------------------+----------+-------------------+
Number of errored trials: 1
+--------------------------------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                                       |   # failures | error file                                                                                                                                      |
|--------------------------------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------|
| MAPPOTrainer_magym_FortAttackOffense_f1da7_00000 |            1 | /workspaces/FortAttack/exp_results/mappo_mlp_FortAttackOffense/MAPPOTrainer_magym_FortAttackOffense_f1da7_00000_0_2023-07-30_01-25-42/error.txt |
+--------------------------------------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "test_fortattack_marllib_env.py", line 29, in <module>
    mappo.render(
  File "/root/MARLlib/marllib/marl/__init__.py", line 333, in render
    self.fit(env, model, stop, **running_params)
  File "/root/MARLlib/marllib/marl/__init__.py", line 316, in fit
    run_cc(self.config_dict, env_instance, model_class, stop=stop)
  File "/root/MARLlib/marllib/marl/algos/run_cc.py", line 194, in run_cc
    results = POlICY_REGISTRY[exp_info["algorithm"]](model, exp_info, run_config, env_info, stop_config,
  File "/root/MARLlib/marllib/marl/algos/scripts/mappo.py", line 112, in run_mappo
    results = tune.run(MAPPOTrainer,
  File "/opt/miniconda/lib/python3.8/site-packages/ray/tune/tune.py", line 624, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [MAPPOTrainer_magym_FortAttackOffense_f1da7_00000])
```

**Comment by Theohhhu** [comment]
Hi,

Have you been able to successfully run [this script](https://github.com/Replicable-MARL/MARLlib/blob/master/examples/load_model.py)? Just a reminder, both the training and loading processes should use the same hyperparameters.

**Comment by Yuxin916** [comment]
Hi, i also have the same issue. Both the training and loading processes should use the same hyperparameters. And here is my error.txt:

Failure # 1 (occurred at 2023-08-11_20-08-33)
Traceback (most recent call last):
  File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 1117, in _process_trial_restore
    self.trial_executor.fetch_result(trial)
  File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(FileNotFoundError): [36mray::MAPPOTrainer.restore_from_object()[39m (pid=27678, ip=10.96.47.191, repr=MAPPOTrainer)
  File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/tune/trainable.py", line 433, in restore_from_object
    self.restore(checkpoint_path)
  File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/tune/trainable.py", line 397, in restore
    with open(checkpoint_path + ".tune_metadata", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tsaisplus/Codes/MARLlib_MuRPE/exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_cadc4_00000_0_2023-08-11_20-08-33/tmpzhugsh9qrestore_from_object/./.tune_metadata'

I set the render restore_path as: 
             restore_path={
                 'params_path': "exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_0b06e_00000_0_2023-08-11_17-54-20/params.json",
                 'model_path': "exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_0b06e_00000_0_2023-08-11_17-54-20/checkpoint_001000",
             },

And here is the tree structure of exp_result:
tsaisplus@XPS-8950:~/Codes/MARLlib_MuRPE/exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_0b06e_00000_0_2023-08-11_17-54-20$ tree
.
├── checkpoint_000200
│   ├── checkpoint-200
│   └── checkpoint-200.tune_metadata
├── checkpoint_000400
│   ├── checkpoint-400
│   └── checkpoint-400.tune_metadata
├── checkpoint_000600
│   ├── checkpoint-600
│   └── checkpoint-600.tune_metadata
├── checkpoint_000800
│   ├── checkpoint-800
│   └── checkpoint-800.tune_metadata
├── checkpoint_001000
│   ├── checkpoint-1000
│   └── checkpoint-1000.tune_metadata
├── checkpoint_001200
│   ├── checkpoint-1200
│   └── checkpoint-1200.tune_metadata
├── events.out.tfevents.1691747667.XPS-8950
├── params.json
├── params.pkl
├── progress.csv
└── result.json

6 directories, 17 files

Appreciate for your help!

**Comment by hccz95** [comment]
you set a wrong model_path. You have to set it to a checkpoint file, instead of a directory.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月11日(星期五) 晚上8:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Replicable-MARL/MARLlib] Error processing restore. (Issue #170)





 
Hi, i also have the same issue. Both the training and loading processes should use the same hyperparameters. And here is my error.txt:
 
Failure # 1 (occurred at 2023-08-11_20-08-33)
 Traceback (most recent call last):
 File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 1117, in _process_trial_restore
 self.trial_executor.fetch_result(trial)
 File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
 result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
 File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
 return func(*args, **kwargs)
 File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/worker.py", line 1625, in get
 raise value.as_instanceof_cause()
 ray.exceptions.RayTaskError(FileNotFoundError): �[36mray::MAPPOTrainer.restore_from_object()�[39m (pid=27678, ip=10.96.47.191, repr=MAPPOTrainer)
 File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/tune/trainable.py", line 433, in restore_from_object
 self.restore(checkpoint_path)
 File "/home/tsaisplus/anaconda3/envs/marllib_MuRPE/lib/python3.8/site-packages/ray/tune/trainable.py", line 397, in restore
 with open(checkpoint_path + ".tune_metadata", "rb") as f:
 FileNotFoundError: [Errno 2] No such file or directory: '/home/tsaisplus/Codes/MARLlib_MuRPE/exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_cadc4_00000_0_2023-08-11_20-08-33/tmpzhugsh9qrestore_from_object/./.tune_metadata'
 
I set the render restore_path as:
 restore_path={
 'params_path': "exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_0b06e_00000_0_2023-08-11_17-54-20/params.json",
 'model_path': "exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_0b06e_00000_0_2023-08-11_17-54-20/checkpoint_001000",
 },
 
And here is the tree structure of exp_result:
 ***@***.***:~/Codes/MARLlib_MuRPE/exp_results/mappo_mlp_simple_spread/MAPPOTrainer_mpe_simple_spread_0b06e_00000_0_2023-08-11_17-54-20$ tree
 .
 ├── checkpoint_000200
 │&nbsp;&nbsp; ├── checkpoint-200
 │&nbsp;&nbsp; └── checkpoint-200.tune_metadata
 ├── checkpoint_000400
 │&nbsp;&nbsp; ├── checkpoint-400
 │&nbsp;&nbsp; └── checkpoint-400.tune_metadata
 ├── checkpoint_000600
 │&nbsp;&nbsp; ├── checkpoint-600
 │&nbsp;&nbsp; └── checkpoint-600.tune_metadata
 ├── checkpoint_000800
 │&nbsp;&nbsp; ├── checkpoint-800
 │&nbsp;&nbsp; └── checkpoint-800.tune_metadata
 ├── checkpoint_001000
 │&nbsp;&nbsp; ├── checkpoint-1000
 │&nbsp;&nbsp; └── checkpoint-1000.tune_metadata
 ├── checkpoint_001200
 │&nbsp;&nbsp; ├── checkpoint-1200
 │&nbsp;&nbsp; └── checkpoint-1200.tune_metadata
 ├── events.out.tfevents.1691747667.XPS-8950
 ├── params.json
 ├── params.pkl
 ├── progress.csv
 └── result.json
 
6 directories, 17 files
 
Appreciate for your help!
