### ISSUE TITLE
Create a custom environment with heterogeneous agents？

### ISSUE THREAD

**Issue by Miracle1207** [Replicable-MARL/MARLlib#177]
In my env, there are two group agents, agents in the same group are homogeneous. While "add_new_env.py" assume all agent same action/obs space.

**Comment by Miracle1207** [comment]
when I try to keep obs and action dim same, I got the following errors:

        # keep obs and action dim same across agents
        # pad_action_space_v0 will auto mask the padding actions
        env = ss.pad_observations_v0(env)
        env = ss.pad_action_space_v0(env)

Traceback (most recent call last):
  File "/home/mqr/code/marllib/main.py", line 243, in <module>
    env = marl.make_env(environment_name="taxai", map_name="TaxAI", abs_path="/home/mqr/code/marllib/marllib/envs/TaxAI/cfg/default.yaml")
  File "/home/mqr/code/marllib/marllib/marl/__init__.py", line 151, in make_env
    env = ENV_REGISTRY[env_config ["env"]] (env_config["env_args"])
  File "/home/mqr/code/marllib/main.py", line 106, in __init__
    env = ss.pad_observations_v0(env)
  File "/home/mqr/anaconda3/envs/marllib/lib/python3.8/site-packages/supersuit/multiagent_wrappers/padding_wrappers.py", line 17, in pad_observations_v0
    assert isinstance(env, AECEnv) or isinstance(env, ParallelEnv), "pad_observations_v0 only accepts an AECEnv or ParallelEnv"
AssertionError: pad_observations_v0 only accepts an AECEnv or ParallelEnv

**Comment by Theohhhu** [comment]
The `supersuit` tool is exclusively designed for use with PettingZoo. Both AECEnv and ParallelEnv serve as environment interfaces within PettingZoo. To utilize `supersuit`, you should start by inheriting either AECEnv or ParallelEnv, and then integrate it accordingly.
