### ISSUE TITLE
Colab notebook does not seem to work.

### ISSUE THREAD

**Issue by MatthewCWeston** [Replicable-MARL/MARLlib#191]
As best I can tell, the Google Colab script in the README is no longer functional. Attempting to run it results in the following error message:

```
Traceback (most recent call last):
  File "marllib_script.py", line 2, in <module>
    from marllib import marl
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/__init__.py", line 25, in <module>
    from marllib.marl.algos import run_il, run_vd, run_cc
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/algos/__init__.py", line 23, in <module>
    from .run_cc import run_cc
  File "/usr/local/lib/python3.8/site-packages/marllib/marl/algos/run_cc.py", line 25, in <module>
    from ray.rllib.utils.framework import try_import_tf, try_import_torch
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/__init__.py", line 7, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/env/__init__.py", line 1, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/usr/local/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 4, in <module>
    import gymnasium as gym
  File "/usr/local/lib/python3.8/site-packages/gymnasium/__init__.py", line 4, in <module>
    from gymnasium.core import (
  File "/usr/local/lib/python3.8/site-packages/gymnasium/core.py", line 9, in <module>
    from gymnasium import spaces
  File "/usr/local/lib/python3.8/site-packages/gymnasium/spaces/__init__.py", line 13, in <module>
    from gymnasium.spaces.box import Box
  File "/usr/local/lib/python3.8/site-packages/gymnasium/spaces/box.py", line 7, in <module>
    from numpy.typing import NDArray
ImportError: cannot import name 'NDArray' from 'numpy.typing' (/usr/local/lib/python3.8/site-packages/numpy/typing/__init__.py)
```

Additionally, the setup script, also in the README, seems to be missing a few compatibility adjustments, though they may be specific to the machine I was running MARLlib on. In case it's of use, here's the process I went through to get it to work:

```
conda create -n marllib python=3.8
conda activate marllib
git clone https://github.com/Replicable-MARL/MARLlib.git && cd MARLlib
pip install --upgrade pip setuptools==65.5.0 wheel==0.38.4
pip install -r requirements.txt
pip install protobuf==3.20.3
cd ./marllib/patch
python add_patch.py -y
cd ...
```

**Comment by fortyMiles** [comment]
@MatthewCWeston I have resolved this bug, which was caused by numpy version.
