### ISSUE TITLE
AttributeError: 'MAPPOTrainer' object has no attribute '_local_ip'

### ISSUE THREAD

**Issue by gyccccccccc** [Replicable-MARL/MARLlib#208]
Hello，when I run the model MAPPO in my custom environment，it turns out the error. Could you plz help me to check?

here is the log:
2023-12-15 15:01:01,514	WARNING worker.py:496 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
:task_name:bundle_reservation_check_func
:actor_name:MAPPOTrainer
2023-12-15 15:01:02,015	WARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!
2023-12-15 15:01:02,015	INFO ppo.py:166 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
2023-12-15 15:01:02,015	INFO trainer.py:770 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
:actor_name:RolloutWorker
[2023-12-15 15:01:02,217 E 22136 7028] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::RolloutWorker.__init__() (pid=22136, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x000001F873ACA100>)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 539, in __init__
    policy_dict = _determine_spaces_for_multi_agent_dict(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1486, in _determine_spaces_for_multi_agent_dict
    raise ValueError(
ValueError: `action_space` not provided in PolicySpec for shared_policy and env does not have an action space OR no spaces received from other workers' env(s) OR no `action_space` specified in config! at time: 1.70262e+09
2023-12-15 15:01:02,217	ERROR actor.py:746 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=22136, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 539, in __init__
    policy_dict = _determine_spaces_for_multi_agent_dict(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1486, in _determine_spaces_for_multi_agent_dict
    raise ValueError(
ValueError: `action_space` not provided in PolicySpec for shared_policy and env does not have an action space OR no spaces received from other workers' env(s) OR no `action_space` specified in config!
:actor_name:RolloutWorker
[2023-12-15 15:01:02,314 E 22136 7028] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::RolloutWorker.__init__()::Exiting (pid=22136, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x000001F873AE2F70>)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 539, in __init__
    policy_dict = _determine_spaces_for_multi_agent_dict(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1486, in _determine_spaces_for_multi_agent_dict
    raise ValueError(
ValueError: `action_space` not provided in PolicySpec for shared_policy and env does not have an action space OR no spaces received from other workers' env(s) OR no `action_space` specified in config! at time: 1.70262e+09
2023-12-15 15:01:02,314	ERROR actor.py:746 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__()::Exiting (pid=22136, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 539, in __init__
    policy_dict = _determine_spaces_for_multi_agent_dict(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1486, in _determine_spaces_for_multi_agent_dict
    raise ValueError(
ValueError: `action_space` not provided in PolicySpec for shared_policy and env does not have an action space OR no spaces received from other workers' env(s) OR no `action_space` specified in config!
[2023-12-15 15:01:02,320 E 22136 7028] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::RolloutWorker.foreach_policy()::Exiting (pid=22136, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x000001F873ACA100>)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1206, in foreach_policy
    for pid, policy in self.policy_map.items()
AttributeError: 'RolloutWorker' object has no attribute 'policy_map' at time: 1.70262e+09
[2023-12-15 15:01:02,375 E 22136 7028] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::MAPPOTrainer.__init__() (pid=22136, ip=127.0.0.1, repr=MAPPOTrainer)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer_template.py", line 137, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 623, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\trainable.py", line 107, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer_template.py", line 147, in setup
    super().setup(config)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 776, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer_template.py", line 171, in _init
    self.workers = self._make_workers(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 858, in _make_workers
    return WorkerSet(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 87, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::RolloutWorker.foreach_policy()::Exiting (pid=22136, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x000001F873ACA100>)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1206, in foreach_policy
    for pid, policy in self.policy_map.items()
AttributeError: 'RolloutWorker' object has no attribute 'policy_map' at time: 1.70262e+09
2023-12-15 15:01:02,375	ERROR actor.py:746 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MAPPOTrainer.__init__() (pid=22136, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer_template.py", line 137, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 623, in __init__
    super().__init__(config, logger_creator)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\trainable.py", line 107, in __init__
    self.setup(copy.deepcopy(self.config))
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer_template.py", line 147, in setup
    super().setup(config)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 776, in setup
    self._init(self.config, self.env_creator)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer_template.py", line 171, in _init
    self.workers = self._make_workers(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 858, in _make_workers
    return WorkerSet(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 87, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::RolloutWorker.foreach_policy()::Exiting (pid=22136, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x000001F873ACA100>)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1206, in foreach_policy
    for pid, policy in self.policy_map.items()
AttributeError: 'RolloutWorker' object has no attribute 'policy_map'
[2023-12-15 15:01:02,397 E 22136 7028] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::MAPPOTrainer.get_auto_filled_metrics()::Exiting (pid=22136, ip=127.0.0.1, repr=MAPPOTrainer)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\trainable.py", line 179, in get_auto_filled_metrics
    NODE_IP: self._local_ip,
AttributeError: 'MAPPOTrainer' object has no attribute '_local_ip' at time: 1.70262e+09
[2023-12-15 15:01:02,917 E 22136 7028] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::MAPPOTrainer.train()::Exiting (pid=22136, ip=127.0.0.1, repr=MAPPOTrainer)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 682, in train
    raise e
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 668, in train
    result = Trainable.train(self)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\trainable.py", line 283, in train
    result = self.step()
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\rllib\agents\trainer_template.py", line 206, in step
    step_results = next(self.train_exec_impl)
AttributeError: 'MAPPOTrainer' object has no attribute 'train_exec_impl' at time: 1.70262e+09
Traceback (most recent call last):
  File "D:/py_learning/MARLlib-master/marllib/envs/base_env/my_merge.py", line 119, in <module>
    mappo.fit(env, model, stop={'episode_reward_mean': 2000, 'timesteps_total': 10000000}, local_mode=True,
  File "D:\py_learning\MARLlib-master\marllib\marl\__init__.py", line 316, in fit
    return run_cc(self.config_dict, env_instance, model_class, stop=stop)
  File "D:\py_learning\MARLlib-master\marllib\marl\algos\run_cc.py", line 194, in run_cc
    results = POlICY_REGISTRY[exp_info["algorithm"]](model, exp_info, run_config, env_info, stop_config,
  File "D:\py_learning\MARLlib-master\marllib\marl\algos\scripts\mappo.py", line 112, in run_mappo
    results = tune.run(MAPPOTrainer,
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\tune.py", line 603, in run
    _report_progress(runner, progress_reporter)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\tune.py", line 68, in _report_progress
    reporter.report(trials, done, sched_debug_str, executor_debug_str)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\progress_reporter.py", line 520, in report
    print(self._progress_str(trials, done, *sys_info))
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\progress_reporter.py", line 279, in _progress_str
    user_metrics = self._infer_user_metrics(trials, self._infer_limit)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\progress_reporter.py", line 325, in _infer_user_metrics
    if not t.last_result:
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\trial.py", line 433, in last_result
    self._get_default_result_or_future()
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\trial.py", line 409, in _get_default_result_or_future
    self._default_result_or_future = ray.get(
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::MAPPOTrainer.get_auto_filled_metrics()::Exiting (pid=22136, ip=127.0.0.1, repr=MAPPOTrainer)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\hp\.conda\envs\marllib\lib\site-packages\ray\tune\trainable.py", line 179, in get_auto_filled_metrics
    NODE_IP: self._local_ip,
AttributeError: 'MAPPOTrainer' object has no attribute '_local_ip'

**Comment by gyccccccccc** [comment]
It's the "D:\py_learning\MARLlib-master\marllib\envs\base_env\exp_results\mappo_mlp_multimerge\MAPPOTrainer_my_merge_multimerge_00c80_00000_0_2023-12-13_18-40-16\params.json"

{
  "batch_mode": "truncate_episodes",
  "clip_param": 0.3,
  "entropy_coeff": 0.01,
  "env": "my_merge_multimerge",
  "evaluation_interval": 50,
  "framework": "torch",
  "kl_coeff": 0.2,
  "lambda": 1.0,
  "lr": 0.0005,
  "model": {
    "custom_model": "Centralized_Critic_Model",
    "custom_model_config": {
      "agent_level_batch_update": false,
      "agent_name_ls": [
        "vehicle1",
        "vehicle2"
      ],
      "algorithm": "mappo",
      "checkpoint_end": true,
      "checkpoint_freq": 50,
      "env": "my_merge",
      "env_args": {
        "map_name": "multimerge"
      },
      "episode_limit": 100,
      "evaluation_interval": 50,
      "force_coop": false,
      "framework": "torch",
      "global_state_flag": true,
      "local_dir": "",
      "local_mode": true,
      "mask_flag": false,
      "model_arch_args": {
        "core_arch": "mlp",
        "encode_layer": "128-128",
        "fc_layer": 2,
        "hidden_state_size": 256,
        "out_dim_fc_0": 128,
        "out_dim_fc_1": 64
      },
      "num_agents": 2,
      "num_cpus_per_worker": 1,
      "num_gpus": 1,
      "num_gpus_per_worker": 0,
      "num_workers": 2,
      "opp_action_in_cc": true,
      "policy_mapping_info": {
        "multimerge": {
          "all_agents_one_policy": true,
          "description": "multi agents merge",
          "one_agent_one_policy": true,
          "team_prefix": "vehicle_"
        }
      },
      "restore_path": {
        "model_path": "",
        "params_path": ""
      },
      "seed": 321,
      "share_policy": "all",
      "space_act": "Discrete(5)",
      "space_obs": "Dict(obs:Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf], [inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf\n inf inf inf inf inf inf inf], (25,), float32))",
      "stop_iters": 9999999,
      "stop_reward": 999999,
      "stop_timesteps": 2000000
    }
  },
  "multiagent": {
    "policies": "{'shared_policy'}",
    "policy_mapping_fn": "<function run_cc.<locals>.<lambda> at 0x0000023968971700>"
  },
  "num_gpus": 1,
  "num_gpus_per_worker": 0,
  "num_sgd_iter": 5,
  "num_workers": 2,
  "seed": 321,
  "sgd_minibatch_size": 1000,
  "simple_optimizer": false,
  "train_batch_size": 1000,
  "use_gae": true,
  "vf_clip_param": 10.0,
  "vf_loss_coeff": 1.0
}

**Comment by Aequatio-Space** [comment]
The actual error is in the front:
```python
raise ValueError(
ValueError: action_space not provided in PolicySpec for shared_policy and env does not have an action space OR no spaces received from other workers' env(s) OR no action_space specified in config.
``` 

It seems that you didn't specify action_space in your environment. You can set relevant properties in custom environment wrapper like:
https://github.com/Replicable-MARL/MARLlib/blob/368c6173577d0f9c0ad70fb5b4b6afa12c864c15/examples/add_new_env.py#L66-L79

Or somehow through the configuration file. I set these properties directly through environment code.

**Comment by gyccccccccc** [comment]
Thank you for your answer :)
