### ISSUE TITLE
How export trained model as a .pt (pytorch ) or ONNX model. 

### ISSUE THREAD

**Issue by manaspalaparthi** [Replicable-MARL/MARLlib#227]
How to export trained model as a .pt (pytorch ) or ONNX model. 

I have fully trained my model and want to deploy the model into the Unity ML agents Env.  I have to export the trained model either in Pytorch or ONNX. 

I could only see one option  "algo.render()" in the documentation.

**Comment by Aequatio-Space** [comment]
Although I do not know how Ray can do that directly, I tried to unwrap a Ray checkpoint and figured out its structure.
First, load the raw checkpoint with `pickle.load`, you will get a dictionary instance, whose value for key "worker" is a `bytes` instance that contains the model weights. Use `pickle.loads` to get the worker status dictionary. select key 'state' and then 'weight', which will be the raw parameters for the network. You may manually pack them into a `.pt` object.

**Comment by Morphlng** [comment]
RLlib's `Policy` class has the function `export_model`, which is used for [exporting raw learning framework](https://github.com/ray-project/ray/blob/72fdf3be605e4aadfd9a8c3f01dd7843c01cb8fd/rllib/policy/policy.py#L601-L615) model with options to save as ONNX model.

So the problem falls back to how to load the checkpoint MARLlib saved. I've personally wrote a [script](https://github.com/Morphlng/MARLlib/blob/main/examples/eval.py) to load the `checkpoint + params.json`. You can reuse the `load_model` function to retreive the policy, and then export it:

```python
from eval import load_model

ckpt = load_model(
    {
        "model_path": "best_model/checkpoint",
        "params_path": "best_model/params.json",
    }
)

env = marl.make_env(environment_name=ckpt.env_name, map_name=ckpt.map_name)
env_instance, env_info = env

# Change the policy name accordingly
policy = ckpt.trainer.get_policy("shared_policy")
model = policy.model
policy.export_model("/directoty/to/save")
```

**Comment by SLKTYHHM** [comment]
> RLlib's `Policy` class has the function `export_model`, which is used for [exporting raw learning framework](https://github.com/ray-project/ray/blob/72fdf3be605e4aadfd9a8c3f01dd7843c01cb8fd/rllib/policy/policy.py#L601-L615) model with options to save as ONNX model.
> 
> So the problem falls back to how to load the checkpoint MARLlib saved. I've personally wrote a [script](https://github.com/Morphlng/MARLlib/blob/main/examples/eval.py) to load the `checkpoint + params.json`. You can reuse the `load_model` function to retreive the policy, and then export it:
> 
> ```python
> from eval import load_model
> 
> ckpt = load_model(
>     {
>         "model_path": "best_model/checkpoint",
>         "params_path": "best_model/params.json",
>     }
> )
> 
> env = marl.make_env(environment_name=ckpt.env_name, map_name=ckpt.map_name)
> env_instance, env_info = env
> 
> # Change the policy name accordingly
> policy = ckpt.trainer.get_policy("shared_policy")
> model = policy.model
> policy.export_model("/directoty/to/save")
> ```

Thank you for your answer.  

I have exported the model with the method. The checkpoint model is got by `marllib.marl.algos.mappo`. 

Then I use it to read my environment's observation. However, there are some errors. At the same time, I analyzed the source code of `ray`, found the forward method of the model in the file `/root/miniconda3/envs/marllib/lib/python3.8/site-packages/marllib/marl/models/zoo/mlp/base_mlp.py`. It has no limits on `state` and `seq_lens` , excepts type. The code is just as follows. So, how do I fix the error to make my model work well? Looking forward to your reply.

```python
@override(TorchModelV2)
def forward(self, input_dict: Dict[str, TensorType],
            state: List[TensorType],
            seq_lens: TensorType) -> (TensorType, List[TensorType]):

    if self.custom_config["global_state_flag"] or self.custom_config["mask_flag"]:
        flat_inputs = input_dict["obs"]["obs"].float()
        # Convert action_mask into a [0.0 || -inf]-type mask.
        if self.custom_config["mask_flag"]:
            action_mask = input_dict["obs"]["action_mask"]
            inf_mask = torch.clamp(torch.log(action_mask), min=FLOAT_MIN)
    else:
        flat_inputs = input_dict["obs"]["obs"].float()

    self.inputs = flat_inputs
    self._features = self.p_encoder(self.inputs)

    output = self.p_branch(self._features)

    if self.custom_config["mask_flag"]:
        output = output + inf_mask

    return output, state
```

My code is as follows. The `obs[0]` is like `{'obs': tensor([10., 11., 10., 10., 11., 14.])}`.

```python
agent = torch.load("exp_results/mappo_mlp_navigation/model.pt")
act = agent.forward(obs[0], [obs[0]["obs"][0]], obs[0]["obs"])
```

The error message shows:

```
Traceback (most recent call last):
  File "/test.py", line 90, in <module>
    act = agent.forward(obs[0], [obs[0]["obs"][0]], obs[0]["obs"])
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/marllib/marl/models/zoo/mlp/cc_mlp.py", line 22, in forward
    _3 = ops.prim.NumToTensor(torch.size(obs, 0))
    _4 = int(_3)
    obs_slice = torch.slice(obs, 1, 0, 6)
                ~~~~~~~~~~~ <--- HERE
    inputs = torch.to(torch.reshape(obs_slice, [_4, 6]), 6)
    _5 = (_0).forward((_1).forward(inputs, ), )

Traceback of TorchScript, original code (most recent call last):
/root/miniconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/modelv2.py(452): _unpack_obs
/root/miniconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/modelv2.py(389): restore_original_dimensions
/root/miniconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/modelv2.py(231): __call__
/root/miniconda3/envs/marllib/lib/python3.8/site-packages/torch/jit/_trace.py(952): trace_module
/root/miniconda3/envs/marllib/lib/python3.8/site-packages/torch/jit/_trace.py(735): trace
/root/miniconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/torch_policy.py(959): export_model
/export_model.py(17): <module>
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```
