### ISSUE TITLE
ERROR:AttributeError: 'MAA2CTrainer' object has no attribute '_local_ip'

### ISSUE THREAD

**Issue by zengya55** [Replicable-MARL/MARLlib#65]
It turns out wrong when I run the example:
`python marl/main.py --algo_config=maa2c --env_config=mpe with env_args.map_name=simple_adversary`

Here the log  is:
/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:91: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.
  warnings.warn(
/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/pettingzoo/utils/conversions.py:105: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.
  warnings.warn(
use fc encoder
2022-11-10 10:48:46,928 WARNING sample.py:401 -- DeprecationWarning: wrapping <function run_cc.<locals>.<lambda> at 0x7f4908387700> with tune.function() is no longer needed
2022-11-10 10:48:47,099 WARNING worker.py:496 -- `ray.get_gpu_ids()` will always return the empty list when called from the driver. This is because Ray does not manage GPU allocations to the driver process.
:task_name:bundle_reservation_check_func
:actor_name:MAA2CTrainer
2022-11-10 10:48:47,183 WARNING deprecation.py:38 -- DeprecationWarning: `simple_optimizer` has been deprecated. This will raise an error in the future!
2022-11-10 10:48:47,183 INFO trainer.py:770 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
[2022-11-10 10:48:47,194 E 10507 10507] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::MAA2CTrainer.__init__() (pid=10507, ip=10.31.217.80, repr=MAA2CTrainer)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 137, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 623, in __init__
    super().__init__(config, logger_creator)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 107, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 147, in setup
    super().setup(config)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 776, in setup
    self._init(self.config, self.env_creator)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 171, in _init
    self.workers = self._make_workers(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 858, in _make_workers
    return WorkerSet(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 110, in __init__
    self._local_worker = self._make_worker(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 406, in _make_worker
    worker = cls(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 584, in __init__
    self._build_policy_map(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1384, in _build_policy_map
    self.policy_map.create_policy(name, orig_cls, obs_space, act_space,
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/policy_map.py", line 143, in create_policy
    self[policy_id] = class_(observation_space, action_space,
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/policy_template.py", line 241, in __init__
    dist_class, logit_dim = ModelCatalog.get_action_dist(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 287, in get_action_dist
    raise NotImplementedError("Unsupported args: {} {}".format(
NotImplementedError: Unsupported args: Discrete(5) None at time: 1.66805e+09
2022-11-10 10:48:47,195 ERROR actor.py:746 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MAA2CTrainer.__init__() (pid=10507, ip=10.31.217.80)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 137, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 623, in __init__
    super().__init__(config, logger_creator)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 107, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 147, in setup
    super().setup(config)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 776, in setup
    self._init(self.config, self.env_creator)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 171, in _init
    self.workers = self._make_workers(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 858, in _make_workers
    return WorkerSet(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 110, in __init__
    self._local_worker = self._make_worker(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 406, in _make_worker
    worker = cls(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 584, in __init__
    self._build_policy_map(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1384, in _build_policy_map
    self.policy_map.create_policy(name, orig_cls, obs_space, act_space,
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/policy_map.py", line 143, in create_policy
    self[policy_id] = class_(observation_space, action_space,
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/policy/policy_template.py", line 241, in __init__
    dist_class, logit_dim = ModelCatalog.get_action_dist(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 287, in get_action_dist
    raise NotImplementedError("Unsupported args: {} {}".format(
NotImplementedError: Unsupported args: Discrete(5) None
[2022-11-10 10:48:47,197 E 10507 10507] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::MAA2CTrainer.get_auto_filled_metrics()::Exiting (pid=10507, ip=10.31.217.80, repr=MAA2CTrainer)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 179, in get_auto_filled_metrics
    NODE_IP: self._local_ip,
AttributeError: 'MAA2CTrainer' object has no attribute '_local_ip' at time: 1.66805e+09
[2022-11-10 10:48:47,701 E 10507 10507] core_worker.cc:1561: Pushed Error with JobID: 01000000 of type: task with message: ray::MAA2CTrainer.train_buffered()::Exiting (pid=10507, ip=10.31.217.80, repr=MAA2CTrainer)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 224, in train_buffered
    result = self.train()
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 682, in train
    raise e
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 668, in train
    result = Trainable.train(self)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 283, in train
    result = self.step()
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 206, in step
    step_results = next(self.train_exec_impl)
AttributeError: 'MAA2CTrainer' object has no attribute 'train_exec_impl' at time: 1.66805e+09
Traceback (most recent call last):
  File "marl/main.py", line 42, in <module>
    run_cc(config_dict)
  File "/home/zyy/Documents/rl/MARLlib/marl/algos/run_cc.py", line 182, in run_cc
    results = POlICY_REGISTRY[config_dict["algorithm"]](config_dict, common_config, env_info_dict, stop)
  File "/home/zyy/Documents/rl/MARLlib/marl/algos/scripts/maa2c.py", line 45, in run_maa2c
    results = tune.run(MAA2CTrainer,
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/tune.py", line 603, in run
    _report_progress(runner, progress_reporter)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/tune.py", line 68, in _report_progress
    reporter.report(trials, done, sched_debug_str, executor_debug_str)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/progress_reporter.py", line 520, in report
    print(self._progress_str(trials, done, *sys_info))
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/progress_reporter.py", line 279, in _progress_str
    user_metrics = self._infer_user_metrics(trials, self._infer_limit)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/progress_reporter.py", line 325, in _infer_user_metrics
    if not t.last_result:
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trial.py", line 433, in last_result
    self._get_default_result_or_future()
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trial.py", line 409, in _get_default_result_or_future
    self._default_result_or_future = ray.get(
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::MAA2CTrainer.get_auto_filled_metrics()::Exiting (pid=10507, ip=10.31.217.80, repr=MAA2CTrainer)
  File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/tune/trainable.py", line 179, in get_auto_filled_metrics
    NODE_IP: self._local_ip,
AttributeError: 'MAA2CTrainer' object has no attribute '_local_ip

**Comment by Theohhhu** [comment]
Hi there,

Seems like your error line is 
File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 287, in get_action_dist
raise NotImplementedError("Unsupported args: {} {}".format( NotImplementedError: Unsupported args: Discrete(5) None
We never run into this bug.
We recommend you run in local mode (ray.yaml) to reduce the error printed.
And please provide your complete config files (params.json) under the experiment log directory for us to check.

**Comment by zengya55** [comment]
> Hi there,
> 
> Seems like your error line is File "/home/zyy/anaconda3/envs/marllib/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 287, in get_action_dist raise NotImplementedError("Unsupported args: {} {}".format( NotImplementedError: Unsupported args: Discrete(5) None We never run into this bug. We recommend you run in local mode (ray.yaml) to reduce the error printed. And please provide your complete config files (params.json) under the experiment log directory for us to check.
> 
> Also, make sure the Ray version is 1.8.0, Gym version 0.21.0, and Pettingzoo version 1.12.0
well, the environment is all right except Pettingzoo the newest. I run the code in local mode but the errors don't change. my 
params.json is  as follows:

{
  "batch_mode": "complete_episodes",
  "entropy_coeff": 0.01,
  "env": "mpe_simple_adversary",
  "evaluation_interval": 10,
  "framework": "torch",
  "lambda": 1.0,
  "lr": 0.0005,
  "model": {
    "custom_model": "Centralized_Critic_Model",
    "custom_model_config": {
      "algo_args": {
        "batch_episode": 10,
        "batch_mode": "complete_episodes",
        "entropy_coeff": 0.01,
        "lambda": 1.0,
        "lr": 0.0005,
        "use_gae": true,
        "vf_loss_coeff": 1.0
      },
      "algorithm": "maa2c",
      "env": "mpe",
      "env_args": {
        "continuous_actions": false,
        "map_name": "simple_adversary",
        "max_cycles": 25
      },
      "episode_limit": 25,
      "evaluation_interval": 10,
      "framework": "torch",
      "global_state_flag": false,
      "local_mode": false,
      "mask_flag": false,
      "model_arch_args": {
        "core_arch": "gru",
        "fc_layer": 1,
        "hidden_state_size": 256,
        "out_dim_fc_0": 128
      },
      "num_agents": 3,
      "num_cpus_per_worker": 1,
      "num_gpus": 0,
      "num_gpus_per_worker": 0,
      "num_workers": 0,
      "opp_action_in_cc": true,
      "policy_mapping_info": {
        "simple_adversary": {
          "all_agents_one_policy": false,
          "description": "one team attack, one team survive",
          "one_agent_one_policy": true,
          "team_prefix": [
            "adversary_",
            "agent_"
          ]
        },
        "simple_crypto": {
          "all_agents_one_policy": false,
          "description": "two team cooperate, one team attack",
          "one_agent_one_policy": true,
          "team_prefix": [
            "eve_",
            "bob_",
            "alice_"
          ]
        },
        "simple_push": {
          "all_agents_one_policy": false,
          "description": "one team target on landmark, one team attack",
          "one_agent_one_policy": true,
          "team_prefix": [
            "adversary_",
            "agent_"
          ]
        },
        "simple_reference": {
          "all_agents_one_policy": true,
          "description": "one team cooperate",
          "one_agent_one_policy": true,
          "team_prefix": [
            "agent_"
          ]
        },
        "simple_speaker_listener": {
          "all_agents_one_policy": true,
          "description": "two team cooperate",
          "one_agent_one_policy": true,
          "team_prefix": [
            "speaker_",
            "listener_"
          ]
        },
        "simple_spread": {
          "all_agents_one_policy": true,
          "description": "one team cooperate",
          "one_agent_one_policy": true,
          "team_prefix": [
            "agent_"
          ]
        },
        "simple_tag": {
          "all_agents_one_policy": false,
          "description": "one team attack, one team survive",
          "one_agent_one_policy": true,
          "team_prefix": [
            "adversary_",
            "agent_"
          ]
        },
        "simple_world_comm": {
          "all_agents_one_policy": false,
          "description": "two team cooperate and attack, one team survive",
          "one_agent_one_policy": true,
          "team_prefix": [
            "adversary_",
            "leaderadversary_",
            "agent_"
          ]
        }
      },
      "seed": 123,
      "share_policy": "group",
      "space_act": "Discrete(5)",
      "space_obs": "Dict(obs:Box(10,))",
      "stop_iters": 9999999,
      "stop_reward": 999999,
      "stop_timesteps": 2000000
    },
    "max_seq_len": 25
  },
  "multiagent": {
    "policies": {
      "policy_adversary_": [
        null,
        "Dict(obs:Box(10,))",
        "Discrete(5)",
        {}
      ],
      "policy_agent_": [
        null,
        "Dict(obs:Box(10,))",
        "Discrete(5)",
        {}
      ]
    },
    "policy_mapping_fn": "<function run_cc.<locals>.<lambda> at 0x7f001819a3a0>"
  },
  "num_gpus": 0,
  "num_gpus_per_worker": 0,
  "num_workers": 0,
  "simple_optimizer": false,
  "train_batch_size": 250,
  "use_gae": true,
  "vf_loss_coeff": 1.0
}

**Comment by Theohhhu** [comment]
Please provide your complete config files (**params.json**) under the experiment log directory (**ray_results/maa2c_gru_xxx**).

**Comment by Theohhhu** [comment]
close as no response

**Comment by DefinitelyNotHilbert** [comment]
Hey, I have the same issue, but with MADDPG (and various other models).


Here's the `params.json`
```
{
  "actor_lr": 0.0005,
  "batch_mode": "complete_episodes",
  "buffer_size": 25000,
  "critic_lr": 0.0005,
  "env": "mpe_simple_adversary",
  "evaluation_interval": 10,
  "framework": "torch",
  "learning_starts": 400,
  "model": {
    "custom_model_config": {
      "algo_args": {
        "actor_lr": 0.0005,
        "batch_episode": 8,
        "batch_mode": "complete_episodes",
        "buffer_size_episode": 1000,
        "critic_lr": 0.0005,
        "learning_starts_episode": 16,
        "n_step": 1,
        "prioritized_replay": false,
        "smooth_target_policy": false,
        "target_network_update_freq_episode": 1,
        "tau": 0.002,
        "twin_q": false
      },
      "algorithm": "maddpg",
      "env": "mpe",
      "env_args": {
        "continuous_actions": false,
        "map_name": "simple_adversary",
        "max_cycles": 25
      },
      "episode_limit": 25,
      "evaluation_interval": 10,
      "framework": "torch",
      "global_state_flag": false,
      "local_mode": true,
      "mask_flag": false,
      "model_arch_args": {
        "core_arch": "gru",
        "fc_layer": 1,
        "hidden_state_size": 256,
        "out_dim_fc_0": 128
      },
      "num_agents": 3,
      "num_cpus_per_worker": 1,
      "num_gpus": 0,
      "num_gpus_per_worker": 0,
      "num_workers": 0,
      "opp_action_in_cc": true,
      "policy_mapping_info": {
        "simple_adversary": {
          "all_agents_one_policy": false,
          "description": "one team attack, one team survive",
          "one_agent_one_policy": true,
          "team_prefix": [
            "adversary_",
            "agent_"
          ]
        },
        "simple_crypto": {
          "all_agents_one_policy": false,
          "description": "two team cooperate, one team attack",
          "one_agent_one_policy": true,
          "team_prefix": [
            "eve_",
            "bob_",
            "alice_"
          ]
        },
        "simple_push": {
          "all_agents_one_policy": false,
          "description": "one team target on landmark, one team attack",
          "one_agent_one_policy": true,
          "team_prefix": [
            "adversary_",
            "agent_"
          ]
        },
        "simple_reference": {
          "all_agents_one_policy": true,
          "description": "one team cooperate",
          "one_agent_one_policy": true,
          "team_prefix": [
            "agent_"
          ]
        },
        "simple_speaker_listener": {
          "all_agents_one_policy": true,
          "description": "two team cooperate",
          "one_agent_one_policy": true,
          "team_prefix": [
            "speaker_",
            "listener_"
          ]
        },
        "simple_spread": {
          "all_agents_one_policy": true,
          "description": "one team cooperate",
          "one_agent_one_policy": true,
          "team_prefix": [
            "agent_"
          ]
        },
        "simple_tag": {
          "all_agents_one_policy": false,
          "description": "one team attack, one team survive",
          "one_agent_one_policy": true,
          "team_prefix": [
            "adversary_",
            "agent_"
          ]
        },
        "simple_world_comm": {
          "all_agents_one_policy": false,
          "description": "two team cooperate and attack, one team survive",
          "one_agent_one_policy": true,
          "team_prefix": [
            "adversary_",
            "leaderadversary_",
            "agent_"
          ]
        }
      },
      "seed": 123,
      "share_policy": "group",
      "space_act": "Discrete(5)",
      "space_obs": "Dict(obs:Box([-100. -100. -100. -100. -100. -100. -100. -100. -100. -100.], [100. 100. 100. 100. 100. 100. 100. 100. 100. 100.], (10,), float32))",
      "stop_iters": 9999999,
      "stop_reward": 999999,
      "stop_timesteps": 2000000
    },
    "max_seq_len": 25
  },
  "multiagent": {
    "policies": {
      "policy_adversary_": [
        null,
        "Dict(obs:Box([-100. -100. -100. -100. -100. -100. -100. -100. -100. -100.], [100. 100. 100. 100. 100. 100. 100. 100. 100. 100.], (10,), float32))",
        "Discrete(5)",
        {}
      ],
      "policy_agent_": [
        null,
        "Dict(obs:Box([-100. -100. -100. -100. -100. -100. -100. -100. -100. -100.], [100. 100. 100. 100. 100. 100. 100. 100. 100. 100.], (10,), float32))",
        "Discrete(5)",
        {}
      ]
    },
    "policy_mapping_fn": "<function run_cc.<locals>.<lambda> at 0x7f04d34fd4c0>"
  },
  "n_step": 1,
  "num_gpus": 0,
  "num_gpus_per_worker": 0,
  "num_workers": 0,
  "prioritized_replay": false,
  "simple_optimizer": false,
  "smooth_target_policy": false,
  "target_network_update_freq": 25,
  "tau": 0.002,
  "train_batch_size": 8,
  "twin_q": false,
  "zero_init_states": true
}
```

**Comment by Theohhhu** [comment]
DDPG algorithm family only supports continuous action space. Turn env args **continuous_actions** to True in mpe.yaml to see if the bug goes away.

**Comment by DefinitelyNotHilbert** [comment]
Thanks, that helped!
